# Generated by Django 5.1.3 on 2024-11-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='categories',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
