# Generated by Django 5.1.3 on 2024-11-24 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
    ]
