# Generated by Django 5.1.3 on 2024-11-25 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_status_alter_project_description'),
        ('task', '0008_remove_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.project'),
            preserve_default=False,
        ),
    ]
